<?xml version="1.0"?>

<robot name="my_manipulator" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="limit_effort"     value="1000.0"  />
    <xacro:property name="limit_lower"      value="${-pi}"  />
    <xacro:property name="limit_upper"      value="${pi}"   />
    <xacro:property name="limit_velocity"   value="0.5"     />
    
    <xacro:property name="base_size"        value="1.5 1.5" />
    <xacro:property name="base_height"      value="0.1"     />
    <xacro:property name="base_height_half" value="${base_height/2.0}" />  

    <xacro:property name="l00"          value="base_link"           />
	<xacro:property name="l01"          value="link_01"             />
	<xacro:property name="l02"          value="link_02"             />
	<xacro:property name="l03"          value="link_03"             />
	<xacro:property name="l04"          value="link_04"             />


	<xacro:property name="R01"          value="0.25"             />
	<xacro:property name="R02"          value="0.2"             />
	<xacro:property name="R03"          value="0.15"             />
	<xacro:property name="R04"          value="0.1"             />
</robot>